[package]
name = "monman"
version = "0.1.0"
authors = ["Markus Røyset <maroider@protonmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.8", features = ["windef", "wingdi", "winuser"] }
bitflags = "1.2.1"
